# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8glFxeRjhGAJ80FmHpwvt6FvT6V0EQE

# 새 섹션
"""

import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display, clear_output

# ----------------------------------------------------------
# 1. SETTINGS (change these freely)
# ----------------------------------------------------------
POSTER_W, POSTER_H = 10, 14      # poster size in "poster units"
BACKGROUND = "#fdf6ec"           # poster background color
SEED = 42                        # same seed = same layout on every redraw

# Color palettes: the Palette slider picks one of these.
PALETTES = {
    "Sunset": ["#ff5e5b", "#ffb400", "#ff8552", "#c1121f", "#780000"],
    "Ocean":  ["#03045e", "#0077b6", "#00b4d8", "#90e0ef", "#caf0f8"],
    "Forest": ["#1b4332", "#2d6a4f", "#52b788", "#95d5b2", "#d8f3dc"],
    "Candy":  ["#ff70a6", "#ff9770", "#ffd670", "#e9ff70", "#70d6ff"],
}
PALETTE_NAMES = list(PALETTES.keys())

# ----------------------------------------------------------
# 2. BLOB SHAPE HELPER
# ----------------------------------------------------------
def make_blob(cx, cy, radius, wobble, seed, n_points=200):
    """Return x, y coordinates of a wobbly circle centered at (cx, cy).
    wobble = 0 gives a perfect circle; higher values give lumpier shapes.
    The seed keeps each blob's shape stable when sliders move."""
    rng = np.random.default_rng(seed)
    theta = np.linspace(0, 2 * np.pi, n_points)
    r = np.full_like(theta, radius)
    for k in range(2, 7):                        # layer a few sine waves
        amp = wobble * radius * rng.uniform(0.2, 1.0) / k
        phase = rng.uniform(0, 2 * np.pi)
        r += amp * np.sin(k * theta + phase)
    return cx + r * np.cos(theta), cy + r * np.sin(theta)

# ----------------------------------------------------------
# 3. YOUR ORIGINAL POSTER DRAWING LOGIC
#    >>> PASTE / ADAPT YOUR OWN CODE INSIDE THIS FUNCTION <<<
#    The function receives the slider values:
#      n_layers -> how many layers to draw
#      wobble   -> how irregular the shapes are
#      colors   -> list of colors from the chosen palette
#    Always draw onto `ax` (not `plt`).
# ----------------------------------------------------------
def draw_original_poster(ax, n_layers, wobble, colors):
    # Placeholder design: overlapping translucent blobs.
    # Replace this loop with your own drawing code.
    for i in range(n_layers):
        rng = np.random.default_rng(SEED + i)
        cx = rng.uniform(1, POSTER_W - 1)
        cy = rng.uniform(1, POSTER_H - 1)
        radius = rng.uniform(1.0, 3.5)
        x, y = make_blob(cx, cy, radius, wobble, seed=SEED + 1000 + i)
        ax.fill(x, y, color=colors[i % len(colors)], alpha=0.55, linewidth=0)

# ----------------------------------------------------------
# 4. STORAGE for blobs added with the "Add blob" button
# ----------------------------------------------------------
added_blobs = []                       # each item: (x, y, radius, seed, color_index)
add_rng = np.random.default_rng()      # unseeded, so every new blob looks different

def draw_added_blobs(ax, wobble, colors):
    for (x, y, radius, seed, color_idx) in added_blobs:
        bx, by = make_blob(x, y, radius, wobble, seed)
        ax.fill(bx, by, color=colors[color_idx % len(colors)],
                alpha=0.75, edgecolor="white", linewidth=1.5)

# ----------------------------------------------------------
# 5. BUILD THE SLIDERS AND BUTTONS
# ----------------------------------------------------------
style = {"description_width": "90px"}
layout = widgets.Layout(width="450px")

layers  = widgets.IntSlider(value=12, min=1, max=30,
                            description="Layers", style=style, layout=layout)
wobble  = widgets.FloatSlider(value=0.5, min=0.0, max=1.5, step=0.05,
                              description="Wobble", style=style, layout=layout)
palette = widgets.IntSlider(value=0, min=0, max=len(PALETTE_NAMES) - 1,
                            description="Palette", style=style, layout=layout)
pos_x   = widgets.FloatSlider(value=POSTER_W / 2, min=0, max=POSTER_W, step=0.1,
                              description="New blob X", style=style, layout=layout)
pos_y   = widgets.FloatSlider(value=POSTER_H / 2, min=0, max=POSTER_H, step=0.1,
                              description="New blob Y", style=style, layout=layout)
add_btn   = widgets.Button(description="Add blob", button_style="success")
clear_btn = widgets.Button(description="Clear added blobs")
out = widgets.Output()                 # the poster is drawn inside this area

# ----------------------------------------------------------
# 6. REDRAW FUNCTION (runs whenever something changes)
# ----------------------------------------------------------
def redraw(*_):
    palette_name = PALETTE_NAMES[palette.value]
    colors = PALETTES[palette_name]
    with out:
        clear_output(wait=True)                  # wipe the previous poster
        fig, ax = plt.subplots(figsize=(6, 8.5))
        ax.set_xlim(0, POSTER_W)
        ax.set_ylim(0, POSTER_H)
        ax.set_aspect("equal")
        ax.set_facecolor(BACKGROUND)
        ax.set_xticks([]); ax.set_yticks([])

        draw_original_poster(ax, layers.value, wobble.value, colors)
        draw_added_blobs(ax, wobble.value, colors)

        # Mark where the next blob will be placed with a "+"
        ax.plot(pos_x.value, pos_y.value, "k+", markersize=16, markeredgewidth=2)
        ax.set_title(f"Palette: {palette_name}")
        plt.show()
        plt.close(fig)                           # free memory

# ----------------------------------------------------------
# 7. CONNECT EVENTS
# ----------------------------------------------------------
# Any slider movement triggers a redraw.
for w in (layers, wobble, palette, pos_x, pos_y):
    w.observe(redraw, names="value")

def on_add(_btn):
    """Place a new blob at the X/Y slider position."""
    added_blobs.append((
        pos_x.value, pos_y.value,
        add_rng.uniform(0.6, 1.8),                 # random size
        int(add_rng.integers(0, 10**6)),           # random shape seed
        int(add_rng.integers(0, 5)),               # random palette color slot
    ))
    redraw()

def on_clear(_btn):
    """Remove only the blobs you added; the base poster stays."""
    added_blobs.clear()
    redraw()

add_btn.on_click(on_add)
clear_btn.on_click(on_clear)

# ----------------------------------------------------------
# 8. SHOW EVERYTHING
# ----------------------------------------------------------
display(widgets.VBox([layers, wobble, palette, pos_x, pos_y,
                      widgets.HBox([add_btn, clear_btn]), out]))
redraw()

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patheffects as pe
from matplotlib.colors import to_rgb
from matplotlib.patches import Rectangle
import ipywidgets as widgets
from IPython.display import display, clear_output

# ----------------------------------------------------------
# 1. SETTINGS (change these freely)
# ----------------------------------------------------------
POSTER_W, POSTER_H = 10, 14          # poster size in "poster units"
SEED = 42                            # same seed = same layout on every redraw
POSTER_TITLE = "Generative Poster"   # title printed at the top of the poster

# Each theme has:
#   bg     -> (top color, bottom color) of the background gradient
#   colors -> colors used for blobs and dots
#   ink    -> color for text, frame, and thin outlines
THEMES = {
    "Cream": {
        "bg": ("#fffdf0", "#f1ead0"),
        "colors": ["#d8b48c", "#ddd8c8", "#e0dcc0", "#c9b79c", "#a68a64"],
        "ink": "#2b2118",
    },
    "Sunset": {
        "bg": ("#5a189a", "#10002b"),
        "colors": ["#ff5e5b", "#ffb400", "#ff8552", "#ffd6a5", "#ff006e"],
        "ink": "#fff4e6",
    },
    "Ocean": {
        "bg": ("#0077b6", "#03045e"),
        "colors": ["#00b4d8", "#48cae4", "#90e0ef", "#caf0f8", "#ffd166"],
        "ink": "#f0fbff",
    },
    "Forest": {
        "bg": ("#1b4332", "#081c15"),
        "colors": ["#52b788", "#95d5b2", "#b7e4c7", "#d8f3dc", "#f4a261"],
        "ink": "#f1faee",
    },
    "Candy": {
        "bg": ("#ffe5ec", "#e0c3fc"),
        "colors": ["#ff70a6", "#ff9770", "#ffd670", "#70d6ff", "#b8f2e6"],
        "ink": "#3d2c4d",
    },
}
THEME_NAMES = list(THEMES.keys())

# Film-grain texture, created once so it does not flicker on redraw.
GRAIN = np.random.default_rng(1).normal(0.5, 0.25, (350, 250)).clip(0, 1)

# ----------------------------------------------------------
# 2. BLOB SHAPE HELPER
# ----------------------------------------------------------
def make_blob(cx, cy, radius, wobble, seed, n_points=240):
    """Return x, y coordinates of a wobbly circle centered at (cx, cy).
    wobble = 0 gives a perfect circle; higher values give lumpier shapes.
    The same seed always gives the same shape, so sliders feel stable."""
    rng = np.random.default_rng(seed)
    theta = np.linspace(0, 2 * np.pi, n_points)
    r = np.full_like(theta, radius)
    for k in range(2, 7):                        # layer a few sine waves
        amp = wobble * radius * rng.uniform(0.2, 1.0) / k
        phase = rng.uniform(0, 2 * np.pi)
        r += amp * np.sin(k * theta + phase)
    return cx + r * np.cos(theta), cy + r * np.sin(theta)

# ----------------------------------------------------------
# 3. POSTER DRAWING LOGIC
#    >>> To use your own design, replace the body of this function. <<<
#    It receives:
#      n_layers -> how many layers to draw
#      wobble   -> how irregular the shapes are
#      theme    -> dict with "colors" and "ink" for the chosen palette
#    Always draw onto `ax` (not `plt`).
# ----------------------------------------------------------
def draw_original_poster(ax, n_layers, wobble, theme):
    colors, ink = theme["colors"], theme["ink"]

    # Step 1: decide the position and size of every layer.
    layers_info = []
    for i in range(n_layers):
        rng = np.random.default_rng(SEED + i)
        cx = rng.uniform(1.0, POSTER_W - 1.0)
        cy = rng.uniform(2.0, POSTER_H - 1.5)
        radius = rng.uniform(1.2, 3.8)
        layers_info.append((radius, cx, cy, i))
    layers_info.sort(reverse=True)               # draw big blobs first, small ones on top

    # Step 2: draw each blob with two thin inner outlines (contour-map look).
    for order, (radius, cx, cy, i) in enumerate(layers_info):
        color = colors[i % len(colors)]
        z = 2 + order * 0.1                      # zorder = stacking order
        x, y = make_blob(cx, cy, radius, wobble, seed=SEED + 1000 + i)
        ax.fill(x, y, color=color, alpha=0.6, linewidth=0, zorder=z)
        for k, scale in enumerate((0.72, 0.44)):
            rx, ry = make_blob(cx, cy, radius * scale, wobble, seed=SEED + 1000 + i)
            ax.plot(rx, ry, color=ink, alpha=0.35 - 0.1 * k,
                    linewidth=0.8, zorder=z + 0.05)

    # Step 3: sprinkle confetti dots.
    rng = np.random.default_rng(SEED + 999)
    n_dots = 35
    xs = rng.uniform(0.8, POSTER_W - 0.8, n_dots)
    ys = rng.uniform(1.8, POSTER_H - 0.8, n_dots)
    sizes = rng.uniform(4, 40, n_dots)
    dot_colors = [colors[j] for j in rng.integers(0, len(colors), n_dots)]
    ax.scatter(xs, ys, s=sizes, c=dot_colors, alpha=0.85, linewidths=0, zorder=40)
    ax.scatter(rng.uniform(0.8, POSTER_W - 0.8, 25),
               rng.uniform(1.8, POSTER_H - 0.8, 25),
               s=3, color=ink, alpha=0.6, linewidths=0, zorder=40)

# ----------------------------------------------------------
# 4. BACKGROUND, GRAIN, FRAME, AND TEXT
# ----------------------------------------------------------
def draw_background(ax, theme):
    """Vertical color gradient from the theme's top color to its bottom color."""
    top = np.array(to_rgb(theme["bg"][0]))
    bottom = np.array(to_rgb(theme["bg"][1]))
    t = np.linspace(0, 1, 256)[:, None, None]    # 0 = bottom row, 1 = top row
    gradient = bottom + (top - bottom) * t       # blend between the two colors
    ax.imshow(gradient, extent=[0, POSTER_W, 0, POSTER_H],
              origin="lower", aspect="auto", zorder=0)

def draw_finishing_touches(ax, theme, theme_name, n_layers, wobble):
    ink = theme["ink"]
    outline_color = theme["bg"][0]               # thin outline keeps the title readable

    # Soft grain over everything for a printed-paper feel.
    ax.imshow(GRAIN, cmap="gray", vmin=0, vmax=1, alpha=0.07,
              extent=[0, POSTER_W, 0, POSTER_H],
              aspect="auto", interpolation="nearest", zorder=55)

    # Thin frame around the poster.
    ax.add_patch(Rectangle((0.35, 0.35), POSTER_W - 0.7, POSTER_H - 0.7,
                           fill=False, edgecolor=ink, linewidth=1.2,
                           alpha=0.8, zorder=60))

    # Title: bold, top-left, drawn on top of the blobs.
    ax.text(0.9, POSTER_H - 0.9, POSTER_TITLE, color=ink, fontsize=26,
            fontweight="bold", va="top", ha="left", zorder=61,
            path_effects=[pe.withStroke(linewidth=3, foreground=outline_color)])

    # Small settings summary at the bottom.
    ax.text(0.9, 0.9, f"{theme_name}  ·  {n_layers} layers  ·  wobble {wobble:.2f}",
            color=ink, fontsize=10, alpha=0.85, va="bottom", zorder=61)

# ----------------------------------------------------------
# 5. STORAGE for blobs added with the "Add blob" button
# ----------------------------------------------------------
added_blobs = []                       # each item: (x, y, radius, seed, color_index)
add_rng = np.random.default_rng()      # unseeded, so every new blob looks different

def draw_added_blobs(ax, wobble, theme):
    colors, ink = theme["colors"], theme["ink"]
    for (x, y, radius, seed, color_idx) in added_blobs:
        bx, by = make_blob(x, y, radius, wobble, seed)
        ax.fill(bx, by, color=colors[color_idx % len(colors)], alpha=0.9,
                edgecolor=ink, linewidth=1.4, zorder=30)
        gx, gy = make_blob(x, y, radius * 1.3, wobble, seed)   # thin outer ring
        ax.plot(gx, gy, color=ink, alpha=0.5, linewidth=0.8, zorder=30)

# ----------------------------------------------------------
# 6. BUILD THE SLIDERS AND BUTTONS
# ----------------------------------------------------------
style = {"description_width": "90px"}
layout = widgets.Layout(width="420px")

layers  = widgets.IntSlider(value=14, min=1, max=30,
                            description="Layers", style=style, layout=layout)
wobble  = widgets.FloatSlider(value=0.55, min=0.0, max=1.5, step=0.05,
                              description="Wobble", style=style, layout=layout)
palette = widgets.IntSlider(value=0, min=0, max=len(THEME_NAMES) - 1,
                            description="Palette", style=style,
                            layout=widgets.Layout(width="300px"))
palette_label = widgets.Label(value=THEME_NAMES[0])      # shows the palette name
pos_x   = widgets.FloatSlider(value=POSTER_W / 2, min=0, max=POSTER_W, step=0.1,
                              description="New blob X", style=style, layout=layout)
pos_y   = widgets.FloatSlider(value=POSTER_H / 2, min=0, max=POSTER_H, step=0.1,
                              description="New blob Y", style=style, layout=layout)
add_btn   = widgets.Button(description="Add blob", button_style="success")
clear_btn = widgets.Button(description="Clear added blobs")
out = widgets.Output()                 # the poster is drawn inside this area

# ----------------------------------------------------------
# 7. REDRAW FUNCTION (runs whenever something changes)
# ----------------------------------------------------------
def redraw(*_):
    theme_name = THEME_NAMES[palette.value]
    theme = THEMES[theme_name]
    palette_label.value = theme_name

    with out:
        clear_output(wait=True)                  # wipe the previous poster
        fig, ax = plt.subplots(figsize=(6, 8.4))
        fig.subplots_adjust(0, 0, 1, 1)          # poster fills the whole figure
        ax.set_axis_off()

        draw_background(ax, theme)
        draw_original_poster(ax, layers.value, wobble.value, theme)
        draw_added_blobs(ax, wobble.value, theme)
        draw_finishing_touches(ax, theme, theme_name, layers.value, wobble.value)

        # Mark where the next blob will go: white "+" under a black "+".
        ax.plot(pos_x.value, pos_y.value, "+", color="white",
                markersize=20, markeredgewidth=4, zorder=70)
        ax.plot(pos_x.value, pos_y.value, "+", color="black",
                markersize=20, markeredgewidth=1.5, zorder=71)

        ax.set_xlim(0, POSTER_W)
        ax.set_ylim(0, POSTER_H)
        ax.set_aspect("equal")
        plt.show()
        plt.close(fig)                           # free memory

# ----------------------------------------------------------
# 8. CONNECT EVENTS
# ----------------------------------------------------------
# Any slider movement triggers a redraw.
for w in (layers, wobble, palette, pos_x, pos_y):
    w.observe(redraw, names="value")

def on_add(_btn):
    """Place a new blob at the X/Y slider position."""
    added_blobs.append((
        pos_x.value, pos_y.value,
        add_rng.uniform(0.6, 1.8),                 # random size
        int(add_rng.integers(0, 10**6)),           # random shape seed
        int(add_rng.integers(0, 5)),               # random palette color slot
    ))
    redraw()

def on_clear(_btn):
    """Remove only the blobs you added; the base poster stays."""
    added_blobs.clear()
    redraw()

add_btn.on_click(on_add)
clear_btn.on_click(on_clear)

# ----------------------------------------------------------
# 9. SHOW EVERYTHING
# ----------------------------------------------------------
display(widgets.VBox([layers, wobble,
                      widgets.HBox([palette, palette_label]),
                      pos_x, pos_y,
                      widgets.HBox([add_btn, clear_btn]), out]))
redraw()

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.collections import PolyCollection
from matplotlib.colors import to_rgb, LinearSegmentedColormap
from matplotlib.patches import Circle, Rectangle
import ipywidgets as widgets
from IPython.display import display, clear_output

# ----------------------------------------------------------
# 1. SETTINGS (change these freely)
# ----------------------------------------------------------
POSTER_W, POSTER_H = 10, 14          # poster size in "poster units"
SEED = 42                            # same seed = same layout on every redraw
POSTER_TITLE = "Generative Poster"   # title printed at the bottom-left
POSTER_YEAR = "2026"                 # small tag at the top-right

# Ribbon geometry: the ribbon follows an arch around this center point.
CENTER_X, CENTER_Y = 5.0, 6.8

# Each theme has:
#   bg     -> (top color, bottom color) of the background gradient
#   colors -> colors the ribbon blends through (also used for orbs and dots)
#   ink    -> color for text, thin lines, and the glass circles
THEMES = {
    "Pastel": {
        "bg": ("#0d0d14", "#000000"),
        "colors": ["#f6a6d8", "#c9a7f5", "#8fd3e8", "#a8e6cf", "#fbe7a1", "#f7b7a3"],
        "ink": "#ffffff",
    },
    "Neon": {
        "bg": ("#0a0014", "#000000"),
        "colors": ["#ff2bd6", "#7a2bff", "#2bd9ff", "#2bff9a", "#f6ff2b"],
        "ink": "#ffffff",
    },
    "Ember": {
        "bg": ("#1a0505", "#000000"),
        "colors": ["#ff4d4d", "#ff9a3d", "#ffd23d", "#ff6fb5", "#8e2bff"],
        "ink": "#fff4e6",
    },
    "Aqua": {
        "bg": ("#02111f", "#000000"),
        "colors": ["#0077b6", "#00b4d8", "#90e0ef", "#caf0f8", "#b8f2e6"],
        "ink": "#f0fbff",
    },
    "Cream": {
        "bg": ("#fffdf0", "#f1ead0"),
        "colors": ["#d8b48c", "#ddd8c8", "#e0dcc0", "#c9b79c", "#a68a64"],
        "ink": "#2b2118",
    },
}
THEME_NAMES = list(THEMES.keys())

# Glass circles: (x, y, radius). Big one top-left, small one, medium one lower-right.
GLASS_CIRCLES = [(3.0, 9.7, 1.5), (6.6, 9.3, 0.35), (6.9, 5.9, 0.85)]

# Film-grain texture, created once so it does not flicker on redraw.
GRAIN = np.random.default_rng(1).normal(0.5, 0.25, (350, 250)).clip(0, 1)

# ----------------------------------------------------------
# 2. HELPERS
# ----------------------------------------------------------
def make_blob(cx, cy, radius, wobble, seed, n_points=240):
    """Return x, y coordinates of a wobbly circle centered at (cx, cy).
    wobble = 0 gives a perfect circle; higher values give lumpier shapes."""
    rng = np.random.default_rng(seed)
    theta = np.linspace(0, 2 * np.pi, n_points)
    r = np.full_like(theta, radius)
    for k in range(2, 7):
        amp = wobble * radius * rng.uniform(0.2, 1.0) / k
        phase = rng.uniform(0, 2 * np.pi)
        r += amp * np.sin(k * theta + phase)
    return cx + r * np.cos(theta), cy + r * np.sin(theta)

def ridge_noise(t, u, seed):
    """Smooth, ridge-like noise in the range [-1, 1].
    t = position along the ribbon, u = position across the ribbon.
    Neighboring strands (similar u) get similar values, so the ridges flow."""
    rng = np.random.default_rng(seed)
    total = np.zeros((len(u), len(t)))
    norm = 0.0
    for k, freq in enumerate((3, 6, 11, 17, 26)):     # low to high frequency
        amp = 1.0 / (k + 1)
        phase = rng.uniform(0, 2 * np.pi)
        coupling = rng.uniform(-4, 4)
        total += amp * np.sin(2 * np.pi * freq * t[None, :] + phase + coupling * u[:, None])
        norm += amp
    return total / norm

# ----------------------------------------------------------
# 3. POSTER DRAWING LOGIC
#    >>> To use your own design, replace the body of this function. <<<
#    It receives:
#      n_layers -> number of bands in the ribbon
#      wobble   -> how strongly the ribbon ruffles
#      theme    -> dict with "colors" and "ink" for the chosen palette
#    Always draw onto `ax` (not `plt`).
# ----------------------------------------------------------
def draw_original_poster(ax, n_layers, wobble, theme):
    colors, ink = theme["colors"], theme["ink"]
    cmap = LinearSegmentedColormap.from_list("theme", colors)

    S = 160                                          # segments along the ribbon
    t = np.linspace(0, 1, S + 1)                     # 0 = ribbon start, 1 = ribbon end
    u = np.linspace(-0.5, 0.5, n_layers + 1)         # -0.5 = inner edge, 0.5 = outer edge

    # Path of the ribbon: an arch that sweeps from lower-left, over the top, to lower-right.
    theta = np.deg2rad(200 - 225 * t)
    R = 3.1 + 0.35 * np.sin(2 * np.pi * 0.8 * t + 0.5)          # distance from the center
    width = 0.5 + 1.6 * np.sin(np.pi * t) ** 1.1                # ribbon is widest in the middle

    # Ruffles: the outer edge ruffles more than the inner edge.
    noise = ridge_noise(t, u, SEED)
    envelope = 0.25 + 0.75 * (u[:, None] + 0.5)
    radial = R[None, :] + u[:, None] * width[None, :] + wobble * 0.5 * envelope * noise
    X = CENTER_X + radial * np.cos(theta)[None, :]
    Y = CENTER_Y + radial * np.sin(theta)[None, :]

    # Soft glow under the ribbon (a few wide, very transparent lines).
    cx_line = CENTER_X + R * np.cos(theta)
    cy_line = CENTER_Y + R * np.sin(theta)
    for lw, a in ((70, 0.03), (45, 0.04), (25, 0.05)):
        ax.plot(cx_line, cy_line, color=cmap(0.5), linewidth=lw, alpha=a,
                solid_capstyle="round", zorder=1)

    # Build one small quadrilateral for every (band, segment) pair.
    p00 = np.stack([X[:-1, :-1], Y[:-1, :-1]], axis=-1)
    p01 = np.stack([X[:-1, 1:],  Y[:-1, 1:]],  axis=-1)
    p11 = np.stack([X[1:, 1:],   Y[1:, 1:]],   axis=-1)
    p10 = np.stack([X[1:, :-1],  Y[1:, :-1]],  axis=-1)
    quads = np.stack([p00, p01, p11, p10], axis=2).reshape(-1, 4, 2)

    # Color: mostly by band, slightly by position along the ribbon.
    band_pos = (np.arange(n_layers) + 0.5) / n_layers
    seg_pos = (np.arange(S) + 0.5) / S
    pos = 0.7 * band_pos[:, None] + 0.3 * seg_pos[None, :]
    rgb = cmap(pos)[..., :3]

    # Shading: brighter on ridge tops, darker in valleys (gives a 3D feel).
    noise_mid = (noise[:-1, :-1] + noise[:-1, 1:] + noise[1:, 1:] + noise[1:, :-1]) / 4
    shade = 0.80 + 0.28 * noise_mid
    rgb = np.clip(rgb * shade[..., None], 0, 1).reshape(-1, 3)

    ribbon = PolyCollection(quads, facecolors=rgb, edgecolors=rgb,
                            linewidths=0.4, zorder=3)
    ax.add_collection(ribbon)

    # Thin ridge lines along every strand.
    for j in range(n_layers + 1):
        ax.plot(X[j], Y[j], color=ink, alpha=0.18, linewidth=0.5, zorder=4)

    # Tiny dots scattered around, like distant stars.
    rng = np.random.default_rng(SEED + 999)
    ax.scatter(rng.uniform(0.6, POSTER_W - 0.6, 40),
               rng.uniform(1.8, POSTER_H - 0.6, 40),
               s=rng.uniform(1, 6, 40), color=ink, alpha=0.5,
               linewidths=0, zorder=2)

def draw_glass_circles(ax, theme):
    """Transparent 'glass' circles sitting on top of the ribbon."""
    ink = theme["ink"]
    for (x, y, r) in GLASS_CIRCLES:
        ax.add_patch(Circle((x, y), r, facecolor=ink, edgecolor="none",
                            alpha=0.06, zorder=20))                       # faint fill
        ax.add_patch(Circle((x, y), r, fill=False, edgecolor=ink,
                            alpha=0.45, linewidth=1.0, zorder=21))        # rim
        ax.add_patch(Circle((x - r * 0.12, y + r * 0.12), r * 0.86, fill=False,
                            edgecolor=ink, alpha=0.15, linewidth=0.8, zorder=21))  # inner highlight

# ----------------------------------------------------------
# 4. BACKGROUND, GRAIN, AND TEXT
# ----------------------------------------------------------
def draw_background(ax, theme):
    """Vertical color gradient from the theme's top color to its bottom color."""
    top = np.array(to_rgb(theme["bg"][0]))
    bottom = np.array(to_rgb(theme["bg"][1]))
    t = np.linspace(0, 1, 256)[:, None, None]    # 0 = bottom row, 1 = top row
    gradient = bottom + (top - bottom) * t
    ax.imshow(gradient, extent=[0, POSTER_W, 0, POSTER_H],
              origin="lower", aspect="auto", zorder=0)

def draw_finishing_touches(ax, theme, theme_name, n_layers, wobble):
    ink, colors = theme["ink"], theme["colors"]

    # Soft grain over everything for a printed feel.
    ax.imshow(GRAIN, cmap="gray", vmin=0, vmax=1, alpha=0.05,
              extent=[0, POSTER_W, 0, POSTER_H],
              aspect="auto", interpolation="nearest", zorder=55)

    # Top-right tag: small colored bar + year.
    ax.add_patch(Rectangle((6.6, POSTER_H - 1.15), 1.5, 0.28,
                           facecolor=colors[2 % len(colors)], edgecolor="none",
                           alpha=0.9, zorder=61))
    ax.text(POSTER_W - 0.9, POSTER_H - 1.0, POSTER_YEAR, color=ink,
            fontsize=9, ha="right", va="center", alpha=0.85, zorder=61)

    # Bottom-left: title with a thin line to its right.
    ax.text(0.9, 1.35, POSTER_TITLE, color=ink, fontsize=18,
            fontweight="bold", va="bottom", ha="left", zorder=61)
    ax.plot([6.1, POSTER_W - 0.9], [1.56, 1.56], color=ink,
            alpha=0.7, linewidth=1.2, zorder=61)

    # Small settings summary under the title.
    ax.text(0.9, 0.85, f"{theme_name}  ·  {n_layers} layers  ·  wobble {wobble:.2f}",
            color=ink, fontsize=8, alpha=0.7, va="bottom", zorder=61)

# ----------------------------------------------------------
# 5. STORAGE for blobs added with the "Add blob" button
# ----------------------------------------------------------
added_blobs = []                       # each item: (x, y, radius, seed, color_index)
add_rng = np.random.default_rng()      # unseeded, so every new blob looks different

def draw_added_blobs(ax, wobble, theme):
    """Added blobs look like glowing orbs: colored body, bright rim, small highlight."""
    colors, ink = theme["colors"], theme["ink"]
    for (x, y, radius, seed, color_idx) in added_blobs:
        color = colors[color_idx % len(colors)]
        bx, by = make_blob(x, y, radius, wobble * 0.5, seed)
        ax.fill(bx, by, color=color, alpha=0.6, edgecolor=ink,
                linewidth=1.2, zorder=30)
        hx, hy = make_blob(x - radius * 0.25, y + radius * 0.25,
                           radius * 0.35, wobble * 0.3, seed + 1)
        ax.fill(hx, hy, color=ink, alpha=0.25, linewidth=0, zorder=31)   # highlight

# ----------------------------------------------------------
# 6. BUILD THE SLIDERS AND BUTTONS
# ----------------------------------------------------------
style = {"description_width": "90px"}
layout = widgets.Layout(width="420px")

layers  = widgets.IntSlider(value=16, min=1, max=30,
                            description="Layers", style=style, layout=layout)
wobble  = widgets.FloatSlider(value=0.7, min=0.0, max=1.5, step=0.05,
                              description="Wobble", style=style, layout=layout)
palette = widgets.IntSlider(value=0, min=0, max=len(THEME_NAMES) - 1,
                            description="Palette", style=style,
                            layout=widgets.Layout(width="300px"))
palette_label = widgets.Label(value=THEME_NAMES[0])      # shows the palette name
pos_x   = widgets.FloatSlider(value=POSTER_W / 2, min=0, max=POSTER_W, step=0.1,
                              description="New blob X", style=style, layout=layout)
pos_y   = widgets.FloatSlider(value=POSTER_H / 2, min=0, max=POSTER_H, step=0.1,
                              description="New blob Y", style=style, layout=layout)
add_btn   = widgets.Button(description="Add blob", button_style="success")
clear_btn = widgets.Button(description="Clear added blobs")
out = widgets.Output()                 # the poster is drawn inside this area

# ----------------------------------------------------------
# 7. REDRAW FUNCTION (runs whenever something changes)
# ----------------------------------------------------------
def redraw(*_):
    theme_name = THEME_NAMES[palette.value]
    theme = THEMES[theme_name]
    palette_label.value = theme_name

    with out:
        clear_output(wait=True)                  # wipe the previous poster
        fig, ax = plt.subplots(figsize=(6, 8.4))
        fig.subplots_adjust(0, 0, 1, 1)          # poster fills the whole figure
        ax.set_axis_off()

        draw_background(ax, theme)
        draw_original_poster(ax, layers.value, wobble.value, theme)
        draw_glass_circles(ax, theme)
        draw_added_blobs(ax, wobble.value, theme)
        draw_finishing_touches(ax, theme, theme_name, layers.value, wobble.value)

        # Mark where the next blob will go: white "+" under a black "+".
        ax.plot(pos_x.value, pos_y.value, "+", color="white",
                markersize=20, markeredgewidth=4, zorder=70)
        ax.plot(pos_x.value, pos_y.value, "+", color="black",
                markersize=20, markeredgewidth=1.5, zorder=71)

        ax.set_xlim(0, POSTER_W)
        ax.set_ylim(0, POSTER_H)
        ax.set_aspect("equal")
        plt.show()
        plt.close(fig)                           # free memory

# ----------------------------------------------------------
# 8. CONNECT EVENTS
# ----------------------------------------------------------
# Any slider movement triggers a redraw.
for w in (layers, wobble, palette, pos_x, pos_y):
    w.observe(redraw, names="value")

def on_add(_btn):
    """Place a new blob at the X/Y slider position."""
    added_blobs.append((
        pos_x.value, pos_y.value,
        add_rng.uniform(0.5, 1.4),                 # random size
        int(add_rng.integers(0, 10**6)),           # random shape seed
        int(add_rng.integers(0, 5)),               # random palette color slot
    ))
    redraw()

def on_clear(_btn):
    """Remove only the blobs you added; the base poster stays."""
    added_blobs.clear()
    redraw()

add_btn.on_click(on_add)
clear_btn.on_click(on_clear)

# ----------------------------------------------------------
# 9. SHOW EVERYTHING
# ----------------------------------------------------------
display(widgets.VBox([layers, wobble,
                      widgets.HBox([palette, palette_label]),
                      pos_x, pos_y,
                      widgets.HBox([add_btn, clear_btn]), out]))
redraw()

"""# 새 섹션"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patheffects as pe
from matplotlib.colors import to_rgb
from matplotlib.patches import Ellipse, Polygon
from scipy.ndimage import gaussian_filter      # already installed in Colab
import ipywidgets as widgets
from IPython.display import display, clear_output

# ----------------------------------------------------------
# 1. SETTINGS (change these freely)
# ----------------------------------------------------------
POSTER_W, POSTER_H = 10, 14          # poster size in "poster units"
W_PX, H_PX = 400, 560                # resolution of the stripe image (higher = sharper, slower)
SEED = 42                            # same seed = same layout on every redraw
POSTER_TITLE = "Generative Poster"   # title printed at the bottom-left

# Each theme has:
#   bg    -> background color
#   warm  -> stripe colors used mostly toward the poster edges
#   cool  -> stripe colors used mostly toward the poster center
#   glow  -> colors of the big soft glowing circles
#   lens  -> color of the small lens / hexagon shapes
#   ink   -> color of the title text and thin lines
THEMES = {
    "Sunrise": {
        "bg": "#ede4cf",
        "warm": ["#e8583c", "#f08a4b", "#f4b24c", "#f6cfa8", "#c8402f", "#f3e0b8"],
        "cool": ["#1f4e6b", "#2d6a7a", "#173a52", "#5b9aa0", "#7fb5b0"],
        "glow": ["#ffe9a8", "#f6a04d", "#f4a3a0", "#ffd9b0"],
        "lens": "#fff6e6",
        "ink": "#2a1d16",
    },
    "Twilight": {
        "bg": "#14172b",
        "warm": ["#ff6b6b", "#ff9f5a", "#ffd166", "#f78fb3", "#ffb8a1"],
        "cool": ["#3a86ff", "#5e60ce", "#48bfe3", "#2b2d6e", "#80ffdb"],
        "glow": ["#ffd6a5", "#ff9ecb", "#ffe66d", "#9bf6ff"],
        "lens": "#fff3d6",
        "ink": "#f6ecd9",
    },
    "Sage": {
        "bg": "#eef0e3",
        "warm": ["#e07a5f", "#f2cc8f", "#d4a373", "#e9c46a", "#f4a261"],
        "cool": ["#264653", "#2a9d8f", "#3d5a40", "#588157", "#a3b18a"],
        "glow": ["#f9f1c9", "#e9c46a", "#f2cc8f", "#dad7cd"],
        "lens": "#fffdf2",
        "ink": "#22301f",
    },
    "Rosewood": {
        "bg": "#f4e7e1",
        "warm": ["#c9184a", "#ff4d6d", "#ff758f", "#ffb3c1", "#f4a261"],
        "cool": ["#590d22", "#800f2f", "#3c1642", "#6d597a", "#b56576"],
        "glow": ["#ffccd5", "#ffb3c1", "#ffe5d9", "#fcd5ce"],
        "lens": "#fff5f0",
        "ink": "#3b0a1e",
    },
}
THEME_NAMES = list(THEMES.keys())

# Big glowing circles: (x, y, radius, opacity, glow color slot)
BIG_ORBS = [
    (2.3, 10.6, 2.1, 0.55, 0),
    (7.2,  8.6, 2.2, 0.60, 0),
    (4.1,  4.7, 1.3, 0.70, 1),
    (1.5,  3.3, 1.0, 0.60, 2),
    (8.3, 11.6, 1.2, 0.40, 2),
    (7.6,  3.9, 0.8, 0.50, 3),
]

# Coordinates of every pixel of the stripe image, in poster units (built once).
_cols, _rows = np.meshgrid(np.arange(W_PX), np.arange(H_PX))
XX = (_cols + 0.5) / W_PX * POSTER_W
YY = POSTER_H - (_rows + 0.5) / H_PX * POSTER_H

# Paper grain texture, created once so it does not flicker on redraw.
GRAIN = np.random.default_rng(1).normal(0, 1, (H_PX, W_PX, 1))

# ----------------------------------------------------------
# 2. HELPERS
# ----------------------------------------------------------
def paint_stripes(canvas, n_stripes, wobble, theme):
    """Paint vertical stripes that fade out at both ends.
    Every stripe has its own seed, so adding layers never moves existing stripes."""
    rows = np.arange(H_PX)[:, None]
    for i in range(n_stripes):
        rng = np.random.default_rng(SEED + i)
        x = rng.uniform(0.03, 0.97)                       # horizontal position (0..1)
        closeness = 1 - abs(x - 0.5) * 2                  # 1 at center, 0 at the edges
        # Cool colors are more likely near the center, warm colors near the edges.
        pool = theme["cool"] if rng.random() < 0.15 + 0.65 * closeness else theme["warm"]
        color = np.array(to_rgb(pool[rng.integers(len(pool))]))

        half = max(1, int(rng.uniform(2, 15) / 2))        # half of the stripe width in pixels
        c0 = max(int(x * W_PX) - half, 0)
        c1 = min(int(x * W_PX) + half, W_PX)
        if c1 <= c0:
            continue

        # Where the stripe starts and ends. Wobble makes the ends more irregular.
        top = (rng.uniform(-0.05, 0.40) + wobble * rng.uniform(-0.08, 0.08)) * H_PX
        bottom = (rng.uniform(0.45, 0.88) + wobble * rng.uniform(-0.08, 0.08)) * H_PX
        fade_top = rng.uniform(0.02, 0.12) * H_PX * (1 + wobble)
        fade_bottom = rng.uniform(0.06, 0.25) * H_PX * (1 + wobble)

        # Opacity along the stripe: 0 -> 1 -> 0 (smooth fade at both ends).
        profile = (np.clip((rows - top) / fade_top, 0, 1) *
                   np.clip((bottom - rows) / fade_bottom, 0, 1))
        profile = profile * profile * (3 - 2 * profile)
        a = (rng.uniform(0.5, 0.95) * profile)[..., None]

        canvas[:, c0:c1] = canvas[:, c0:c1] * (1 - a) + color * a

def add_orb(canvas, cx, cy, radius, color, alpha, wobble, seed):
    """Paint one soft glowing circle onto the stripe image.
    The edge is blurry, the center is brighter, and wobble makes the outline lumpy."""
    r_max = radius * 1.5
    c0 = max(int((cx - r_max) / POSTER_W * W_PX), 0)
    c1 = min(int((cx + r_max) / POSTER_W * W_PX) + 1, W_PX)
    r0 = max(int((POSTER_H - (cy + r_max)) / POSTER_H * H_PX), 0)
    r1 = min(int((POSTER_H - (cy - r_max)) / POSTER_H * H_PX) + 1, H_PX)
    if c1 <= c0 or r1 <= r0:
        return

    dx = XX[r0:r1, c0:c1] - cx
    dy = YY[r0:r1, c0:c1] - cy
    dist = np.hypot(dx, dy)
    angle = np.arctan2(dy, dx)

    # Lumpy radius: a few sine waves around the circle.
    rng = np.random.default_rng(seed)
    rad = np.full_like(angle, radius)
    for k in range(2, 6):
        rad += (wobble * radius * 0.12 * rng.uniform(0.3, 1.0) / (k - 1)
                * np.sin(k * angle + rng.uniform(0, 2 * np.pi)))

    d = dist / rad                                        # 0 at center, 1 at the edge
    mask = np.clip((1.0 - d) / 0.35, 0, 1)                # soft edge in the outer 35%
    mask = mask * mask * (3 - 2 * mask)
    core = np.clip(1 - d / 0.6, 0, 1)[..., None]          # brighter core

    base = np.array(to_rgb(color))
    rgb = base + (1 - base) * 0.45 * core                 # blend toward white in the core
    a = (alpha * mask)[..., None]
    canvas[r0:r1, c0:c1] = canvas[r0:r1, c0:c1] * (1 - a) + rgb * a

# ----------------------------------------------------------
# 3. POSTER DRAWING LOGIC
#    >>> To use your own design, replace the body of this function. <<<
#    It must return an RGB image array (values 0..1) of shape (H_PX, W_PX, 3).
#      n_layers -> slider: layers (here: groups of stripes)
#      wobble   -> slider: how irregular things are
#      theme    -> dict of colors for the chosen palette
# ----------------------------------------------------------
def draw_original_poster(n_layers, wobble, theme):
    canvas = np.ones((H_PX, W_PX, 3)) * np.array(to_rgb(theme["bg"]))

    paint_stripes(canvas, n_layers * 6, wobble, theme)    # 6 stripes per layer

    for i, (x, y, r, alpha, gi) in enumerate(BIG_ORBS):
        add_orb(canvas, x, y, r, theme["glow"][gi % len(theme["glow"])],
                alpha, wobble, SEED + 500 + i)

    # Blobs added with the "Add blob" button are painted as glowing circles too.
    for (x, y, radius, seed, color_idx) in added_blobs:
        add_orb(canvas, x, y, radius, theme["glow"][color_idx % len(theme["glow"])],
                0.8, wobble, seed)

    # Dreamy glow: mix the sharp image with a blurred copy of itself.
    blurred = gaussian_filter(canvas, sigma=(7, 7, 0))
    canvas = 0.82 * canvas + 0.18 * blurred

    canvas = canvas + GRAIN * 0.015                       # paper grain
    return np.clip(canvas, 0, 1)

# ----------------------------------------------------------
# 4. SMALL LENS SHAPES, HIGHLIGHTS, AND TEXT (drawn on top)
# ----------------------------------------------------------
def draw_lenses(ax, theme):
    """Small pale ellipses and tall hexagons floating over the stripes."""
    rng = np.random.default_rng(SEED + 777)
    lens = theme["lens"]
    for _ in range(18):
        x = rng.uniform(0.8, POSTER_W - 0.8)
        y = rng.uniform(2.4, POSTER_H - 0.8)              # keep the title area clear
        opacity = rng.uniform(0.55, 0.95)
        if rng.random() < 0.7:                            # ellipse
            ax.add_patch(Ellipse((x, y), rng.uniform(0.5, 1.0), rng.uniform(0.3, 0.5),
                                 facecolor=lens, edgecolor="none",
                                 alpha=opacity, zorder=10))
        else:                                             # tall hexagon
            sx, sy = rng.uniform(0.18, 0.3), rng.uniform(0.4, 0.7)
            pts = np.array([(0, 1), (0.6, 0.5), (0.6, -0.5),
                            (0, -1), (-0.6, -0.5), (-0.6, 0.5)]) * [sx, sy] + [x, y]
            ax.add_patch(Polygon(pts, closed=True, facecolor=lens,
                                 edgecolor="white", linewidth=0.6,
                                 alpha=opacity, zorder=10))

def draw_added_highlights(ax, theme):
    """A small bright spot on each added blob so it looks like glass."""
    for (x, y, radius, seed, color_idx) in added_blobs:
        ax.add_patch(Ellipse((x - radius * 0.25, y + radius * 0.25),
                             radius * 0.45, radius * 0.3,
                             facecolor=theme["lens"], edgecolor="none",
                             alpha=0.85, zorder=12))

def draw_text(ax, theme, theme_name, n_layers, wobble):
    ink = theme["ink"]
    # Title: bottom-left, with a thin outline in the background color for readability.
    ax.text(0.9, 1.6, POSTER_TITLE, color=ink, fontsize=24,
            fontweight="bold", va="bottom", ha="left", zorder=61,
            path_effects=[pe.withStroke(linewidth=4, foreground=theme["bg"])])
    ax.plot([0.9, 6.0], [1.42, 1.42], color=ink, alpha=0.8, linewidth=1.2, zorder=61)
    ax.text(0.9, 0.95, f"{theme_name}  ·  {n_layers} layers  ·  wobble {wobble:.2f}",
            color=ink, fontsize=8, alpha=0.75, va="bottom", zorder=61)

# ----------------------------------------------------------
# 5. STORAGE for blobs added with the "Add blob" button
# ----------------------------------------------------------
added_blobs = []                       # each item: (x, y, radius, seed, color_index)
add_rng = np.random.default_rng()      # unseeded, so every new blob looks different

# ----------------------------------------------------------
# 6. BUILD THE SLIDERS AND BUTTONS
# ----------------------------------------------------------
style = {"description_width": "90px"}
layout = widgets.Layout(width="420px")

layers  = widgets.IntSlider(value=16, min=1, max=30,
                            description="Layers", style=style, layout=layout)
wobble  = widgets.FloatSlider(value=0.5, min=0.0, max=1.5, step=0.05,
                              description="Wobble", style=style, layout=layout)
palette = widgets.IntSlider(value=0, min=0, max=len(THEME_NAMES) - 1,
                            description="Palette", style=style,
                            layout=widgets.Layout(width="300px"))
palette_label = widgets.Label(value=THEME_NAMES[0])      # shows the palette name
pos_x   = widgets.FloatSlider(value=POSTER_W / 2, min=0, max=POSTER_W, step=0.1,
                              description="New blob X", style=style, layout=layout)
pos_y   = widgets.FloatSlider(value=POSTER_H / 2, min=0, max=POSTER_H, step=0.1,
                              description="New blob Y", style=style, layout=layout)
add_btn   = widgets.Button(description="Add blob", button_style="success")
clear_btn = widgets.Button(description="Clear added blobs")
out = widgets.Output()                 # the poster is drawn inside this area

# ----------------------------------------------------------
# 7. REDRAW FUNCTION (runs whenever something changes)
# ----------------------------------------------------------
def redraw(*_):
    theme_name = THEME_NAMES[palette.value]
    theme = THEMES[theme_name]
    palette_label.value = theme_name

    image = draw_original_poster(layers.value, wobble.value, theme)

    with out:
        clear_output(wait=True)                  # wipe the previous poster
        fig, ax = plt.subplots(figsize=(6, 8.4))
        fig.subplots_adjust(0, 0, 1, 1)          # poster fills the whole figure
        ax.set_axis_off()

        ax.imshow(image, extent=[0, POSTER_W, 0, POSTER_H],
                  origin="upper", interpolation="bilinear", zorder=0)
        draw_lenses(ax, theme)
        draw_added_highlights(ax, theme)
        draw_text(ax, theme, theme_name, layers.value, wobble.value)

        # Mark where the next blob will go: white "+" under a black "+".
        ax.plot(pos_x.value, pos_y.value, "+", color="white",
                markersize=20, markeredgewidth=4, zorder=70)
        ax.plot(pos_x.value, pos_y.value, "+", color="black",
                markersize=20, markeredgewidth=1.5, zorder=71)

        ax.set_xlim(0, POSTER_W)
        ax.set_ylim(0, POSTER_H)
        ax.set_aspect("equal")
        plt.show()
        plt.close(fig)                           # free memory

# ----------------------------------------------------------
# 8. CONNECT EVENTS
# ----------------------------------------------------------
# Any slider movement triggers a redraw.
for w in (layers, wobble, palette, pos_x, pos_y):
    w.observe(redraw, names="value")

def on_add(_btn):
    """Place a new glowing blob at the X/Y slider position."""
    added_blobs.append((
        pos_x.value, pos_y.value,
        add_rng.uniform(0.5, 1.4),                 # random size
        int(add_rng.integers(0, 10**6)),           # random shape seed
        int(add_rng.integers(0, 4)),               # random glow color slot
    ))
    redraw()

def on_clear(_btn):
    """Remove only the blobs you added; the base poster stays."""
    added_blobs.clear()
    redraw()

add_btn.on_click(on_add)
clear_btn.on_click(on_clear)

# ----------------------------------------------------------
# 9. SHOW EVERYTHING
# ----------------------------------------------------------
display(widgets.VBox([layers, wobble,
                      widgets.HBox([palette, palette_label]),
                      pos_x, pos_y,
                      widgets.HBox([add_btn, clear_btn]), out]))
redraw()